name: Run Knip against external projects

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - run: bun link

      - name: Test Knip against create-typescript-app
        uses: actions/checkout@v3
        with:
          repository: JoshuaKGoldberg/create-typescript-app
          path: create-typescript-app
      - run: cd create-typescript-app && bun install
      - run: bun knip --directory create-typescript-app

      - name: Test Knip against slonik
        uses: actions/checkout@v3
        with:
          repository: gajus/slonik
          path: slonik
      - run: cd slonik && bun install
      - run: bun knip --directory slonik

      - name: Test Knip against 10ten-ja-reader
        uses: actions/checkout@v3
        with:
          repository: birchill/10ten-ja-reader
          path: 10ten-ja-reader
      - run: cd 10ten-ja-reader && bun install
      - run: bun knip --directory 10ten-ja-reader

      - name: Test Knip against DefinitelyTyped-tools
        uses: actions/checkout@v3
        with:
          repository: microsoft/DefinitelyTyped-tools
          path: DefinitelyTyped-tools
      - run: cd DefinitelyTyped-tools && bun install || true # bun/pnpm
      - run: bun knip --directory DefinitelyTyped-tools
